Repository Leap-MERN-2023/re-star, pull requests merged in 2024-04, with the labels that each got.

#125 add super admin restaurant check
  client/src/components/sections/superAdmin/restaurantCheck.tsx
Labels: documentation

#127 getReviewById and postReview done with frontend
  client/src/app/details/[id]/page.tsx
  client/src/components/sections/admin/review-modal/index.tsx
  client/src/components/sections/details/DetailPicture/index.tsx
  client/src/components/sections/details/tabs/index.tsx
  client/src/components/sections/details/tabs/reviewTab.tsx
  client/src/components/sections/restaurantCard/index.tsx
  client/src/context/FavoritesProvider.tsx
  client/src/context/ReviewProvider.tsx
  client/src/interface/review/index.tsx
  server/src/controller/favorite.ts
  server/src/controller/review.ts
  server/src/model/favorite.ts
  server/src/routes/review.ts
Labels: coding

#133 menu update front
  client/src/app/details/page.tsx
  client/src/app/page.tsx
  client/src/components/sections/admin/admin-menu-tab/index.tsx
  client/src/components/sections/admin/adminMenuView/index.tsx
  client/src/components/sections/admin/editOrg/index.tsx
  client/src/components/sections/admin/menu-modal/index.tsx
  client/src/components/sections/details/tabs/reviewTab.tsx
  server/src/controller/menu.ts
  server/src/model/menu.ts
Labels: enhancement, coding

#136 70 delete review
  client/src/app/details/[id]/page.tsx
  client/src/components/sections/details/MainInfo/index.tsx
  client/src/components/sections/restaurantCard/index.tsx
Labels: bug

#138 dark mode and review bugs
  client/public/images/mainLogo.png
  client/src/app/globals.css
  client/src/app/layout.tsx
  client/src/app/page.tsx
  client/src/components/sections/details/tabs/reviewTab.tsx
  client/src/components/sections/home/CollectionCard/index.tsx
  client/src/components/sections/home/Search/index.tsx
  client/src/components/sections/navbar/footer/index.tsx
  client/src/components/sections/navbar/header/index.tsx
  client/src/components/sections/navbar/header/themeThoggler.tsx
  client/src/components/sections/restaurantCard/index.tsx
  client/src/context/ThemeProvider.tsx
Labels: coding

#160 userprofile change start, about us
  client/src/app/aboutUs/page.tsx
  client/src/components/sections/aboutUs/index.tsx
  client/src/components/sections/navbar/footer/index.tsx
  client/src/components/sections/userProfile/index.tsx
Labels: enhancement

#172 139 updated review
  client/src/components/sections/admin/review-modal/index.tsx
  client/src/components/sections/details/tabs/index.tsx
  client/src/components/sections/details/tabs/reviewTab.tsx
  client/src/context/ReviewProvider.tsx
  client/src/interface/review/index.tsx
  server/src/controller/review.ts
  server/src/routes/review.ts
Labels: coding

#180 146 who we are
  client/src/app/aboutUs/page.tsx
  client/src/app/profile/page.tsx
  client/src/app/userProfile/page.tsx
  client/src/components/index.ts
  client/src/components/sections/aboutUs/index.tsx
  client/src/components/sections/navbar/header/user-nav.tsx
  client/src/components/sections/userProfile/index.tsx
  client/src/components/userSettings/index.tsx
Labels: enhancement

#183 explore page
  client/src/app/details/[id]/page.tsx
  client/src/app/page.tsx
  client/src/app/super-admin/page.tsx
  client/src/components/sections/explore/index.tsx
  client/src/components/sections/explore/searchMap.tsx
  client/src/components/sections/superAdmin/restaurantCheck.tsx
  client/src/context/RestaurantProvider.tsx
  server/src/routes/org.ts
Labels: coding

#187 vercel.json
  server/vercel.json
Labels: coding

#190 front base api url
  client/.env
  client/src/utils/myAxios.ts
Labels: bug, coding

#206 populate bug and user change bug fix
  client/package-lock.json
  client/package.json
  client/src/app/layout.tsx
  client/src/components/sections/details/MainInfo/index.tsx
  client/src/components/sections/details/tabs/reviewTab.tsx
  client/src/components/sections/userProfile/index.tsx
  client/src/context/UserProvider.tsx
  server/src/controller/review.ts
Labels: bug, coding

#213 bug fix
  client/src/components/sections/details/tabs/index.tsx
  client/src/components/sections/details/tabs/reviewTab.tsx
  client/src/components/userSettings/index.tsx
Labels: bug

#224 bugs
  client/src/components/sections/auth/login/index.tsx
  client/src/components/sections/details/MainInfo/index.tsx
  client/src/components/sections/navbar/header/main-nav.tsx
  client/src/components/sections/navbar/header/responsive-nav.tsx
  client/src/components/sections/navbar/header/user-nav.tsx
  client/src/components/sections/restaurantCard/index.tsx
  client/src/context/FavoritesProvider.tsx
  client/src/context/ReviewProvider.tsx
  server/src/controller/review.ts
Labels: bug, coding

#227 user location
  client/src/components/sections/admin/admin-menu-tab/index.tsx
  client/src/components/sections/admin/editOrgMenu/index.tsx
  client/src/components/sections/admin/menu-modal/index.tsx
  client/src/components/sections/explore/searchMap.tsx
  client/src/context/UserLocationContext.js
  client/src/context/UserProvider.tsx
  client/src/interface/user/index.ts
  server/src/controller/menu.ts
Labels: coding

#231 deploy v1
  client/src/app/details/page.tsx
  client/src/app/layout.tsx
  client/src/app/not-found.tsx
  client/src/components/sections/admin/index.tsx
Labels: bug

#236 bugs
  client/src/components/sections/admin/menu-modal/index.tsx
  client/src/context/MenuProvider.tsx
  client/src/context/UserProvider.tsx
  server/src/controller/menu.ts
  server/src/uploads/heloise-de-villepin-mR4HMHkDeY0-unsplash.jpg
Labels: coding

#243 v6
  client/.env
  client/src/components/sections/admin/menu-modal/index.tsx
  client/src/components/sections/favorite/favoriteCard/index.tsx
  client/src/components/sections/restaurantCard/index.tsx
Labels: bug

#245 v7
  client/src/components/sections/explore/searchMap.tsx
Labels: bug

#253 v9
  client/.env
  client/src/components/sections/admin/index.tsx
  client/src/components/sections/details/tabs/menuTab.tsx
  client/src/components/sections/navbar/header/main-nav.tsx
  client/src/components/userSettings/index.tsx
  client/src/context/UserProvider.tsx
  client/src/interface/user/index.ts
Labels: bug

#258 review card wrap
  client/src/components/sections/details/tabs/index.tsx
  client/src/components/sections/details/tabs/reviewTab.tsx
Labels: bug
