Repository Leap-MERN-2023/re-star, pull requests merged in 2024-03, with the labels that each got.

#13 User Profile start
  client/src/components/userProfile/index.tsx
Labels: good first issue

#15 Update README.md
  README.md
Labels: documentation

#17 add detail edit
  client/package-lock.json
  client/package.json
  client/src/app/details/page.tsx
  client/src/app/page.tsx
  client/src/components/sections/details/Cards/index.tsx
  client/src/components/sections/details/DetailPicture/index.tsx
  client/src/components/sections/details/Pictures/index.tsx
  client/src/components/sections/details/Review/index.tsx
  client/src/components/sections/details/tabs/index.tsx
  client/src/components/sections/home/Search/index.tsx
Labels: coding

#21 add detail page design
  client/package-lock.json
  client/package.json
  client/src/app/details/page.tsx
  client/src/components/icons/index.tsx
  client/src/components/sections/details/DetailSearch/index.tsx
  client/src/components/sections/details/MainInfo/index.tsx
  client/src/components/sections/details/Review/index.tsx
  client/src/components/sections/details/tabs/accountTab.tsx
  client/src/components/sections/details/tabs/index.tsx
  client/src/components/sections/details/tabs/menuTab.tsx
  client/src/components/sections/details/tabs/photosTab.tsx
  client/src/components/sections/details/tabs/reviewTab.tsx
  client/src/components/sections/home/Search/index.tsx
Labels: documentation

#29 edit homepage & detailpage
  client/public/images/food1.png
  client/public/images/food2.png
  client/public/images/food3.png
Labels: duplicate

#40 34 review modal
  client/package-lock.json
  client/package.json
  client/src/components/review-modal/index.tsx
  client/src/components/sections/details/MainInfo/index.tsx
Labels: coding

#44 add review backend
  client/src/app/layout.tsx
  client/src/components/review-modal/index.tsx
  client/src/context/ReviewProvider.tsx
  client/src/interface/index.ts
  client/src/interface/review/index.tsx
  server/src/controller/review.ts
  server/src/index.ts
  server/src/routes/review.ts
Labels: coding

#47 header edit for loggedUser
  client/src/components/sections/auth/login/index.tsx
  client/src/components/sections/navbar/header/index.tsx
  client/src/components/sections/navbar/header/main-nav.tsx
  client/src/components/sections/navbar/header/user-nav.tsx
  client/src/context/UserProvider.tsx
Labels: coding

#57 restaurant card ver1
  client/src/components/sections/restaurantCard/index.tsx
Labels: coding

#60 delete, update organization
  server/src/controller/org.ts
  server/src/routes/org.ts
Labels: coding

#68 54 update restaurant front
  client/src/components/sections/editRestaurant/index.tsx
Labels: coding

#86 add category super admin
  client/src/app/super-admin/page.tsx
  client/src/components/sections/superAdmin/addCategory.tsx
  client/src/components/sections/superAdmin/index.tsx
  client/src/context/CategoryProvider.tsx
  server/src/controller/category.ts
  server/src/routes/category.ts
  server/src/uploads/1.avif
  server/src/uploads/2.avif
  server/src/uploads/4.avif
  server/src/uploads/image 13.png
  server/src/uploads/image_14-removebg-preview.png
  server/src/uploads/istockphoto-954315540-612x612.jpg
Labels: documentation

#89 update Org card
  client/src/components/sections/restaurantCard/index.tsx
Labels: coding

#103 zoy bilguun conflict fix
  client/src/app/admin/page.tsx
  client/src/app/details/[id]/page.tsx
  client/src/app/page.tsx
  client/src/components/sections/details/DetailPicture/index.tsx
  client/src/components/sections/restaurantCard/index.tsx
  client/src/context/CategoryProvider.tsx
  client/src/context/RestaurantProvider.tsx
  client/src/interface/restaurant/index.ts
  server/src/controller/category.ts
  server/src/controller/org.ts
  server/src/routes/org.ts
Labels: bug

#105 menu modal, provider, context
  client/src/components/menu-modal/index.tsx
  client/src/components/sections/details/MainInfo/index.tsx
  client/src/context/MenuProvider.tsx
  client/src/interface/restaurant/index.ts
Labels: new feature

#108 add menu, provider, context
  client/src/components/menu-modal/index.tsx
  client/src/context/MenuProvider.tsx
  client/src/interface/restaurant/index.ts
  server/src/controller/menu.ts
  server/src/model/menu.ts
Labels: coding
